<div class="page-Guide-section1of2">
    <div class="Divider"></div>
    <div class="Grid Separator SyncHeight" media-small="Separator--vertical" media-wide="!Separator--vertical">
        <div class="Grid-col" media-wide="Grid-1of2">
            <a class="Link Link--block Panel Panel--link Panel--small Panel--alignCenter bordered Panel--stacked Panel--tiny" href="/ru-ru/news/23529209" data-analytics="homepage-panel" data-analytics-placement="Patch Notes Blog" media-wide="hide"><div class="Panel-bg" data-background-image="https://bnetcmsus-a.akamaihd.net/cms/template_resource/PWZ91SH6P3CC1599671841130.jpg"></div><div class="Panel-area SyncHeight-item"><div class="Panel-box"><div class="Panel-content"><h3 class="Panel-subtitle">Shadowlands</h3><h2 class="Panel-title">Описание обновления</h2><div class="Panel-buttons"></div></div></div></div></a><a class="Link Link--block Panel Panel--link bordered hide Panel--tiny Panel--stacked Panel--stretched Panel--alignCenter Panel--overflowing" href="/ru-ru/news/23529209" data-analytics="homepage-panel" data-analytics-placement="Patch Notes Blog" media-wide="!hide" media-huge="!Panel--stretched"><div class="Panel-bg" data-background-image="https://bnetcmsus-a.akamaihd.net/cms/template_resource/PWZ91SH6P3CC1599671841130.jpg"><div class="Panel-fg"></div></div><div class="Panel-area SyncHeight-item"><div class="Panel-box"><div class="Panel-content"><h3 class="Panel-subtitle">Shadowlands</h3><h2 class="Panel-title">Описание обновления</h2><div class="Panel-buttons"></div></div></div></div></a></div>
        <div class="Grid-col" media-wide="Grid-1of2">
            <a class="Link Link--block Panel Panel--link Panel--small Panel--alignCenter bordered Panel--stacked Panel--tiny" href="/ru-ru/news/23580183" data-analytics="homepage-panel" data-analytics-placement="Hotfixes Blog" media-wide="hide"><div class="Panel-bg" data-background-image="https://bnetcmsus-a.akamaihd.net/cms/template_resource/YJ5F66MYA0XE1599671840973.jpg"></div><div class="Panel-area SyncHeight-item"><div class="Panel-box"><div class="Panel-content"><h3 class="Panel-subtitle">Последние изменения</h3><h2 class="Panel-title">Срочные исправления</h2><div class="Panel-buttons"></div></div></div></div></a><a class="Link Link--block Panel Panel--link bordered hide Panel--tiny Panel--stacked Panel--stretched Panel--alignCenter Panel--overflowing" href="/ru-ru/news/23580183" data-analytics="homepage-panel" data-analytics-placement="Hotfixes Blog" media-wide="!hide" media-huge="!Panel--stretched"><div class="Panel-bg" data-background-image="https://bnetcmsus-a.akamaihd.net/cms/template_resource/YJ5F66MYA0XE1599671840973.jpg"><div class="Panel-fg"></div></div><div class="Panel-area SyncHeight-item"><div class="Panel-box"><div class="Panel-content"><h3 class="Panel-subtitle">Последние изменения</h3><h2 class="Panel-title">Срочные исправления</h2><div class="Panel-buttons"></div></div></div></div></a></div>
    </div>
</div>
